### ISSUE TITLE
Test data missing from distribution

### ISSUE THREAD

**Issue by pghmcfc** [jib/archive-tar-new#27]
The test data files t/src/long/foo.txz and t/src/short/foo.txz are missing from the Archive-Tar-2.34.tar.gz distribution, causing the tests to fail if the xz support modules are available.

**Comment by mbeijen** [comment]
This has been fixed in Archive::Tar 2.36, 02/02/2020, __probably__ because of your reported issue? Archive::Tar 2.34 was only released 1 day prior.

**Comment by pghmcfc** [comment]
I guess so. Anyway, it's fixed now.
